/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\cote_droit.glb 
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";

export function CoteDroit(props) {
  const { nodes, materials } = useGLTF("/cote_droit.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
        material={materials["lambert2SG.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cote_droit.glb");
