/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\toit.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Toit(props) {
  const { nodes, materials } = useGLTF("/toit.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial
          attach="material"
          color={0x000000}
          roughness={0.4}
          metalness={0.1}
          opacity={0.2}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/toit.glb");
